# Generated by Django 5.2.1 on 2025-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTracer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_sku', models.CharField(max_length=255)),
                ('prod_price', models.CharField(max_length=255)),
                ('prod_url', models.CharField(max_length=255)),
            ],
        ),
    ]
