# Generated by Django 5.2.1 on 2025-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_pricestable_productstable_delete_producttracer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(help_text='Product URL or SKU entered by user', max_length=500)),
                ('request_type', models.CharField(choices=[('url', 'URL'), ('sku', 'SKU')], default='url', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or error messages')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
