# Generated by Django 5.2.1 on 2025-08-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_productrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRequest',
        ),
    ]
